// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofbhoebgllkfmlcvtanr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mYmhvZWJnbGxrZm1sY3Z0YW5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDgxMDAsImV4cCI6MjA2MTY4NDEwMH0.tqKPlDAVHGJeQ2QBHdzgNJRp2HMvi6ho4mvcI5HpT1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Configurações otimizadas para alta capacidade
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'x-my-custom-header': 'my-app-name',
    },
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});